## Copyright(C) 2010 - 2014 Basefount Software Limited.
## and/or its licensors.  All rights reserved.
##
## The coded instructions, statements, computer programs, and/or
## related material (collectively the "Data") in these files contain
## unpublished information proprietary to Basefount Technology
## Limitd. ("Basefount") and/or its licensors, which is
## protected by Chinese copyright law and by international treaties.
##
## The Data is provided for use exclusively by You. You have the right 
## to use, modify, and incorporate this Data into other products for 
## purposes authorized by the Basefount software license agreement, 
## without fee.
##
## The copyright notices in the Software and this entire statement, 
## including the above license grant, this restriction and the 
## following disclaimer, must be included in all copies of the 
## Software, in whole or in part, and all derivative works of 
## the Software, unless such copies or derivative works are solely 
## in the form of machine-executable object code generated by a 
## source language processor.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
## BASEFOUNT DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR
## IMPLIED WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES
## OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
## PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
## TRADE PRACTICE. IN NO EVENT WILL BASEFOUNT AND/OR ITS LICENSORS 
## BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
## DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF BASEFOUNT 
## AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
## OR PROBABILITY OF SUCH DAMAGES.
##
## ===================================================================
## -

##+
##=====================================================================
##   Module Name:
##      Mcd3DelightRMFunction.py
##   Description:
##       Parse the shader info with shaderinfo.exe!
##=====================================================================
##-

import maya.cmds as cmds;
import maya.mel as mel;
import os;
import McdGeneral
import McdSimpleCmd
import unicodedata
import platform
import re

def McdParse3DelightRMShader( nodeName, shaderType, orgPath = "" ):
    # get shader info, and fill
    # the dyanmic attribute
    
    isFullCmd = False
    delightPath = ""
    if platform.system() == "Darwin":
        isFullCmd = True
        delightPath = os.getenv("DELIGHT")
        if delightPath == "" or delightPath == None:
            raise Exception("Cannot find DELIGHT path.");
    
    # get shader path
    shaderPath = cmds.getAttr(nodeName + ".fileName");
    if shaderPath == "":
        cmds.confirmDialog(t = "Error", m = "Please specify shader firstly.");
        return
    
    # parse path
    if (not os.access(shaderPath, os.R_OK)):
        cmds.confirmDialog(t = "Error", m = "Shader path have not been setup correctly.");
        return
        
    # make sense the path
    correctShaderPath = shaderPath.replace("\\", "/")
    cmds.setAttr(nodeName + ".fileName", correctShaderPath, type = "string");
    
    # delete all the renderman attribute:
    attrInfoList = cmds.listAttr(nodeName);
    for i in range(len(attrInfoList)):
        if (attrInfoList[i].find("rman_")>=0):
            try:
                cmds.deleteAttr(nodeName + "." + attrInfoList[i]);
            except:
                pass

    # fetch parameters information
    if (shaderPath.find(".sdl") > 0):
        if isFullCmd:
            cmdString = delightPath  + '/bin/' + 'shaderinfo -t "' + shaderPath + '"';
        else:
            cmdString = 'shaderinfo -t "' + shaderPath + '"';
        shaderInfo = os.popen(cmdString).read()
        
    elif (shaderPath.find(".slo") > 0):
        cmdString = 'sloinfo "' + shaderPath + '"';
        shaderInfo = os.popen(cmdString).read()
        shaderInfo = formattingTable(shaderInfo)
        
    else:
        raise Exception("Please select .sdl or .slo again.");

    
    if shaderInfo == "_NULL_":
        raise Exception("3Delight path has not been setup correctly, re-install 3delight may solve this problem.");

    shaderInfoNew = ""
    shaderInfoRaw = shaderInfo.split("\n");
    for i in range(len(shaderInfoRaw)):
        try:
            shaderInfoRaw[i].encode("ascii", "ignore")
            shaderInfoNew += shaderInfoRaw[i] + "||"
        except:
            pass
        
    try:
        if shaderType == 0:
            if shaderInfoRaw[1] != "surface":
                #print shaderInfoRaw[1]
                cmds.confirmDialog(t = "Error", m = "Only support surface shader.\nYou select a " + shaderInfoRaw[1] + " shader")
                cmds.setAttr(nodeName + ".fileName", orgPath, type = "string");
                return;
        elif shaderType == 2:
            if shaderInfoRaw[1] != "displacement":
                cmds.confirmDialog(t = "Error", m = "Only support displacement shader.\nYou select a " + shaderInfoRaw[1] + " shader")
                cmds.setAttr(nodeName + ".fileName", orgPath, type = "string");
                return;
    except:
        raise Exception("3Delight path has not been setup correctly, re-install 3delight may solve this problem.");
    
    cmds.setAttr(nodeName + ".shaderInfo", shaderInfoNew, type = "string")
    
    # parse and, add dynamic attribute, again:
    for i in range(len(shaderInfoRaw)):
        if (i == 0 or i == 1 or i == 2):
            if i == 0:
                shaderName = shaderInfoRaw[0]
            if i == 1:
                shaderType = shaderInfoRaw[1]
            if i == 2:
                attrNum = shaderInfoRaw[2]
            
        else:
            # default parameters parse:
            if (shaderInfoRaw[i].find(',') > 0):
                paramRaw = shaderInfoRaw[i].split(",")
                
                attrName = paramRaw[0]
                attrType = paramRaw[3]
                defValue = paramRaw[6]
                
                valueSet = defValue.split(" ")
                nbAttr = len(valueSet)
                
                if attrType == "string":
                    cmds.addAttr(nodeName, ln = "rman_" + attrName, dt = "string");
                    cmds.setAttr(nodeName + ".rman_" + attrName, valueSet[0], type = "string")
                else:
                    if nbAttr == 1:
                        cmds.addAttr(nodeName, ln = "rman_" + attrName, at = "float", k = 1, dv = float(valueSet[0]));
                    elif nbAttr == 3:
                        cmds.addAttr(nodeName, ln = "rman_" + attrName, at = "float3",\
                                                                                k = 1);
                        cmds.addAttr(nodeName, ln = "rman_" + attrName + "X", at = "float", p = "rman_" + attrName,\
                                                                                k = 1, dv = float(valueSet[0]));
                        cmds.addAttr(nodeName, ln = "rman_" + attrName + "Y", at = "float", p = "rman_" + attrName,\
                                                                                k = 1, dv = float(valueSet[1]));
                        cmds.addAttr(nodeName, ln = "rman_" + attrName + "Z", at = "float", p = "rman_" + attrName,\
                                                                                k = 1, dv = float(valueSet[2]));
                    
                
    # shaderType
    # get shader type
    if (type == "light"):
        cmds.setAttr(nodeName + ".shaderString", "LightSource", type = "string");
    elif (type == "surface"):
        cmds.setAttr(nodeName + ".shaderString",  "Surface", type = "string");
    elif (type == "volume"):
        cmds.setAttr(nodeName + ".shaderString", "Atmosphere", type = "string");
        
        
    mcd_constructShaderString( nodeName );
    
    
def mcd_constructShaderString( nodeName ):
    #--------------------------------
    # PrewviewRIB button in shader AE.
    #   get shader attr info, and
    #   generate RIB for that shader
    #--------------------------------
    
    #   get shader path
    shaderPath = cmds.getAttr(nodeName + ".fileName");
    if shaderPath == "":
        cmds.confirmDialog(t = "Error", m = "Please specify shader firstly.");
        raise Exception("Please specify shader firstly.");
    
    #   parse path
    if (not os.access(shaderPath, os.R_OK)):
        cmds.confirmDialog(t = "Error", m = "Shader path have not been setup correctly.");
        raise Exception("Shader path have not been setup correctly.");
        
    # if path ok, get shader name
    shaderInfo = cmds.getAttr(nodeName + ".shaderInfo")
    #extraParam = cmds.getAttr(nodeName + ".extraParameters")
    shaderInfoRaw = shaderInfo.split("||");
    
    shaderName = shaderInfoRaw[0]
    shaderType = shaderInfoRaw[1]
    attrNum = shaderInfoRaw[2]
    
    ribParamString = shaderName + ' '
    
    for i in range(int(attrNum)):
        paramRaw = shaderInfoRaw[3 + i].split(",")
        
        attrName = paramRaw[0]
        attrType = paramRaw[3]
        defValue = paramRaw[6]
        
        valueSet = defValue.split(' ')
        nbAttr = len(valueSet)
        
        if attrType == "string":
            # deal with string:
            currentVal = cmds.getAttr(nodeName + ".rman_" + attrName)
            if currentVal != valueSet[0]:
                ribString = '"' + attrName + '" ' + '["' + currentVal + '"]'
                ribParamString += ribString + ' '
        else:
            # deal with number:
            if nbAttr == 1 or nbAttr == 3:
                if nbAttr == 1:
                    currentVal = cmds.getAttr(nodeName + ".rman_" + attrName)
                    if not McdGeneral.isFloatEqual(currentVal, float(valueSet[0])):
                        ribString = '"' + attrName + '" ' + '[' + str(currentVal) + ']'
                        ribParamString += ribString + ' '
                else:
                    currentVal = cmds.getAttr(nodeName + ".rman_" + attrName)
                    if not McdGeneral.isFloatEqual(currentVal[0][0], float(valueSet[0])) \
                            or not McdGeneral.isFloatEqual(currentVal[0][1], float(valueSet[1]))\
                            or not McdGeneral.isFloatEqual(currentVal[0][2], float(valueSet[2])):
                        ribString = '"' + attrName + '" ' + '[' \
                                    + str(currentVal[0][0]) + ' ' + str(currentVal[0][1]) + ' ' + str(currentVal[0][2]) + \
                                    ']'
                        ribParamString += ribString + ' '

    cmds.setAttr(nodeName + ".shaderString", ribParamString, type = "string")
            
    
def McdTransformTexture():
    # get output path and make sure it is writable
    globalNode = McdSimpleCmd.McdListMcdGlobal()
    gtx = cmds.getAttr(globalNode + ".genTexFile")
        
    alreadyDone = []
    
    isFullCmd = False
    delightPath = ""
    if platform.system() == "Darwin":
        print "in apple"
        isFullCmd = True
        delightPath = os.getenv("DELIGHT")
        if delightPath == "" or delightPath == None:
            cmds.confirmDialog(t = "Error", m = "Cannot find DELIGHT path.")
            return

    # walk through all the file(texture) node and get texture path set, out color connection
    fileNode = cmds.ls(type = "file")
    
    # progress window
    counter = 0
    totalCount = len(fileNode)
    cmds.progressWindow( title = "Generating .tex File", progress = 0, \
                      min = 0, max = 100, \
                      status = 'Complete: 0%', isInterruptable = True )
    
    for i in range(len(fileNode)):
        # check node itself:
        imagePath = cmds.getAttr(fileNode[i] + ".fileTextureName")
        if imagePath in alreadyDone:
            continue
        else:
            alreadyDone.append(imagePath)
            
        if not os.access(imagePath, os.R_OK):
            continue
        
        if not isPermitedFormat(imagePath):
            continue
        
        isRightPlug = False
        # should connect to color or displacement plug
        allConns = cmds.listConnections(fileNode[i], d = True, s = False, p = True)
        if allConns != None and allConns != []:
            for j in range(len(allConns)):
                if allConns[j].find(".color") > 0 or \
                                        allConns[j].find(".transparency") > 0 or \
                                        allConns[j].find(".displacement") > 0:
                    isRightPlug = True
                    break
        
        if not isRightPlug:
            continue
        
        #collect information:                            # imagePath:  d:/abe_c/rook_1.tif
        canBeRand = True
        # test last underscore
        lastUSId = imagePath.rfind('_')
        if lastUSId < 0:
            canBeRand = False
            
        orgExt = os.path.splitext(imagePath)[1]                 # orgExt      .tif
        if orgExt == '':
            continue # no extension, skip directly.
            
        if canBeRand:
            orgNamePre = ""
            for k in range(lastUSId+1):
                orgNamePre += imagePath[k]                      # orgNamePre  d:/abe_c/rook_
            orgNamePost = imagePath.split(orgNamePre)[-1];      # orgNamePost 1.tif
            orgNumPartStr = orgNamePost.split(orgExt)[0]        #             "1"
            if orgNumPartStr.isdigit():
                numPartInt = int(orgNumPartStr)                 #             1
                numPartStr = str(numPartInt)                    #             "1"
                
                fullPathNew = orgNamePre + numPartStr + orgExt  #             d:/abe_c/rook_1.tif
                
                if not os.path.exists(fullPathNew):
                    canBeRand = False
                
            else:
                canBeRand = False
    
            
        if not canBeRand:
            newTexPath = imagePath.replace(orgExt, ".tex")      # newImage:   d:/abe_c/rook_1.tex
            # subtitude and generate tex file:
            if gtx == 1:
                #create directly:
                if isFullCmd:
                    cmdString = delightPath + '/bin/' + 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                else:    
                    cmdString = 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                os.popen(cmdString)
            else:
                #if exist, dont do any thing
                if not os.access(newTexPath, os.R_OK):
                    #if doesn't, create it
                    if isFullCmd:
                        cmdString = delightPath + '/bin/' + 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                    else:
                        cmdString = 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                    os.popen(cmdString)
        else:
            # while cycle and do all possiable files
            currentNumInt = numPartInt
            while True:
                newImagePath = orgNamePre + str(currentNumInt) + orgExt
                newTexPath = orgNamePre + str(currentNumInt) + ".tex"
                
                currentNumInt += 1 # increasement
                
                if os.path.exists(newImagePath):
                    if gtx == 1:
                        if isFullCmd:
                            cmdString = delightPath + '/bin/' + 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                        else:
                            cmdString = 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                        os.popen(cmdString)
                    else:
                        #if exist, dont do any thing
                        if not os.access(newTexPath, os.R_OK):
                            #if doesn't, create it
                            if isFullCmd:
                                cmdString = delightPath + '/bin/' + 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                            else:
                                cmdString = 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                            os.popen(cmdString)
                else:
                    break
        
        ## /////////////////////////////////////////////////////
        if cmds.progressWindow( query = True, isCancelled = True ):
            break
        counter += 1
        amount = float(counter) / float(totalCount) * 100.0
        cmds.progressWindow( edit = True, progress = amount, status=("Complete: " + str(amount) + "%" ) )
    cmds.progressWindow( endProgress=1 )
    
    
    
    
    # walk through all the rm node and get string attribute, if accessable, transform it
    sfNode = cmds.ls(type = "McdRMShader")
    dpNode = cmds.ls(type = "McdRMDispMat")
    rmNode = []
    rmNode.extend(sfNode)
    rmNode.extend(dpNode)
    
    # progress window
    counter = 0
    totalCount = len(rmNode)
    cmds.progressWindow( title = "Generating .tex RM", progress = 0, \
                      min = 0, max = 100, \
                      status = 'Complete: 0%', isInterruptable = True )
    
    for i in range(len(rmNode)):
        allAttrs = cmds.listAttr(rmNode[i])
        for j in range(len(allAttrs)):
            if allAttrs[j].find("rman_") == 0:
                value = cmds.getAttr(rmNode[i] + '.' + allAttrs[j])
                if value != None and value != "" and value != []:
                    if not isPermitedFormat(value):
                        continue;
                        
                    if os.access(str(value), os.R_OK):  #only deal with accessable path
                        imagePath = value
                        
                        if not os.path.isabs(imagePath):    #bypass non-abs path
                            continue;
                        
                        if imagePath in alreadyDone:    # check is already done
                            continue
                        else:
                            alreadyDone.append(imagePath)
                        
                        #collect information:                            # imagePath:  d:/abe_c/rook_1.tif
                        canBeRand = True
                        
                        lastUSId = imagePath.rfind('_') # test last underscore
                        if lastUSId < 0:
                            canBeRand = False
                            
                        orgExt = os.path.splitext(imagePath)[1]                 # orgExt      .tif
                        if orgExt == '':
                            continue                                            # no extension, skip directly.
                            
                        if canBeRand:
                            orgNamePre = ""
                            for k in range(lastUSId+1):
                                orgNamePre += imagePath[k]                      # orgNamePre  d:/abe_c/rook_
                            orgNamePost = imagePath.split(orgNamePre)[-1];      # orgNamePost 1.tif
                            orgNumPartStr = orgNamePost.split(orgExt)[0]        #             "1"
                            if orgNumPartStr.isdigit():
                                numPartInt = int(orgNumPartStr)                 #             1
                                numPartStr = str(numPartInt)                    #             "1"
                                
                                fullPathNew = orgNamePre + numPartStr + orgExt  # d:/abe_c/rook_1.tif
                                
                                if not os.path.exists(fullPathNew):
                                    canBeRand = False
                                
                            else:
                                canBeRand = False
                                
                            
                        if not canBeRand:
                            newTexPath = imagePath.replace(orgExt, ".tex")      # newImage:   d:/abe_c/rook_1.tex
                            # subtitude and generate tex file:
                            if gtx == 1:
                                #create directly:
                                if isFullCmd:
                                    cmdString = delightPath + '/bin/' + 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                                else:
                                    cmdString = 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                                os.popen(cmdString)
                            else:
                                #if exist, dont do any thing
                                if not os.access(newTexPath, os.R_OK):
                                    #if doesn't, create it
                                    if isFullCmd:
                                        cmdString = delightPath + '/bin/' + 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                                    else:
                                        cmdString = 'tdlmake "' + imagePath + '" "' + newTexPath +'"'
                                    os.popen(cmdString)
                        else:
                            # while cycle and do all possiable files
                            currentNumInt = numPartInt
                            while True:
                                newImagePath = orgNamePre + str(currentNumInt) + orgExt
                                newTexPath = orgNamePre + str(currentNumInt) + ".tex"
                                
                                currentNumInt += 1 # increasement
                                
                                if os.path.exists(newImagePath):
                                    if gtx == 1:
                                        if isFullCmd:
                                            cmdString = delightPath + '/bin/' + 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                                        else:
                                            cmdString = 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                                        os.popen(cmdString)
                                    else:
                                        #if exist, dont do any thing
                                        if not os.access(newTexPath, os.R_OK):
                                            #if doesn't, create it
                                            if isFullCmd:
                                                cmdString = delightPath + '/bin/' + 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                                            else:
                                                cmdString = 'tdlmake "' + newImagePath + '" "' + newTexPath +'"'
                                            os.popen(cmdString)
                                else:
                                    break
                                
        ## /////////////////////////////////////////////////////
        if cmds.progressWindow( query = True, isCancelled = True ):
            break
        counter += 1
        amount = float(counter) / float(totalCount) * 100.0
        cmds.progressWindow( edit = True, progress = amount, status=("Complete: " + str(amount) + "%" ) )
    cmds.progressWindow( endProgress=1 )
                                
def isPermitedFormat(value):
    # TIFF, JPEG, GIF, IFF, SGI, PIC, PSD, TGA
    strValue = str(value)
    if strValue.find(".tif") > 0:
        return True
    if strValue.find(".jpg") > 0:
        return True
    if strValue.find(".tga") > 0:
        return True
    if strValue.find(".tex") > 0:
        return True
    if strValue.find(".iff") > 0:
        return True    
    if strValue.find(".exr") > 0:
        return True
    if strValue.find(".gif") > 0:
        return True
    if strValue.find(".sgi") > 0:
        return True
    if strValue.find(".psd") > 0:
        return True
    if strValue.find(".png") > 0:
        return True
    if strValue.find(".pic") > 0:
        return True
    return False
        
def formattingTable(shaderInfo):
#    
#surface "plastic"
#    "Ks" "parameter uniform float"
#		Default value: 0.500000
#    "Kd" "parameter uniform float"
#		Default value: 0.500000
#    "Ka" "parameter uniform float"
#		Default value: 1.000000
#    "roughness" "parameter uniform float"
#		Default value: 0.100000
#    "specularcolor" "parameter uniform color"
#		Default value: "rgb" [1.000000 1.000000 1.000000]
    
    #print shaderInfo
    
    resultString = ""
    
    shaderInfoSegRaw = shaderInfo.split("\n")
    shaderInfoSeg = []
    #print shaderInfoSegRaw
    if McdGeneral.McdIsBlank(shaderInfoSegRaw):
        return ""
    for i in range(len(shaderInfoSegRaw)):
        if shaderInfoSegRaw[i] == "":
            continue
        temp = shaderInfoSegRaw[i].replace("    ", "")
        temp = temp.replace("\t", "")
        shaderInfoSeg.append(temp)
        
    if McdGeneral.McdIsBlank(shaderInfoSeg):
        return ""
    
# --- >
#surface "plastic"
#"Ks" "parameter uniform float"
#Default value: 0.500000
#"Kd" "parameter uniform float"
#Default value: 0.500000
#"Ka" "parameter uniform float"
#Default value: 1.000000
#"roughness" "parameter uniform float"
#Default value: 0.100000
#"specularcolor" "parameter uniform color"
#Default value: "rgb" [1.000000 1.000000 1.000000]
    
    resultString = ""
    shaderNameNTypeRaw = shaderInfoSeg[0].split(" ")
    if len(shaderNameNTypeRaw) != 2:
        return ""
    if shaderNameNTypeRaw[1].find("\"") < 0:
        return ""
    
    resultString += shaderNameNTypeRaw[1].split("\"")[1] + "\n"
    resultString += shaderNameNTypeRaw[0] + "\n"
    
    
    # statistic
    nbParam = 0
    paramList = []
    for i in range((len(shaderInfoSeg)-1)/2):
        paramRaw = shaderInfoSeg[i*2+1]
        defValRaw = shaderInfoSeg[i*2+2]
        if paramRaw.find("parameter") > 0 and defValRaw.find("Default") >=0:
            # init:
            paramString = ""
            
            paramRaw2 = paramRaw.replace('"', '')
            # param
            paramSeg = paramRaw2.split(" ")
            if len(paramSeg) != 4:
                continue
            for j in range(4):
                paramString += paramSeg[j] + ","
                
            #default val:
            defValSegMain = defValRaw.split("Default value: ")
            defValRaw2 = defValSegMain[1]
            if defValRaw2.find('""') >= 0:
                #string
                paramString += "<none>,0,"
            elif defValRaw2.find('"') >= 0:
                #vector
                defValSeg = defValRaw2.split('"')
                paramString += defValSeg[1] + ","
                paramString += "0,"
                temp = defValSeg[2].replace("[", "")
                temp = temp.replace("]", "")
                defValSeg3 = temp.split(" ")
                rawLen = len(defValSeg3)
                for j in range(rawLen):
                    if defValSeg3[j] != "":
                        if j != rawLen-1:
                            paramString += defValSeg3[j] + " "
                        else:
                            paramString += defValSeg3[j]
                
            else:
                #singlenumber
                paramString += "<none>,0,"
                paramString += defValRaw2
                
            paramList.append(paramString)
            
            nbParam +=1
            
    resultString += str(nbParam) + "\n"
    for i in range(len(paramList)):
        resultString += paramList[i] + "\n"
    
#plastic
#surface
#5
#Ks,parameter,uniform,float,<none>,0,0.5
#Kd,parameter,uniform,float,<none>,0,0.5
#Ka,parameter,uniform,float,<none>,0,1
#roughness,parameter,uniform,float,<none>,0,0.1
#specularcolor,parameter,uniform,color,rgb,0,1 1 1
    
    #print resultString
    
    return resultString
        
def McdRearrangeShaderset():
    
    globalNode = McdGeneral.McdGetMcdGlobalNode()
    ribPath = cmds.getAttr(globalNode + ".cmdMaster[15]")
    
    print "in script"
    print ribPath
    
    if not os.access(ribPath, os.W_OK):
        return
    
    f = open(ribPath, "r")
    
    shaderContents = ""
    ribContents = ""
    startShader = False
    counter = 0
    nextLineStr = "\n"
    for lineContents in f.readlines():
        
        if counter == 0:
            if lineContents.find("\r\n")>0:
                nextLineStr = "\r\n"
        
        if not startShader:
            if lineContents.find('  Surface "') >= 0:
                shaderContents += 'ArchiveBegin "McdShader' + str(counter) + '" ' + nextLineStr
                shaderContents += lineContents
                startShader = True
                ribContents += '  ReadArchive "McdShader' + str(counter) + '" ' + nextLineStr
                counter += 1
                continue
                
            ribContents += lineContents
                
        else:
            if lineContents.find('  Procedural "') >= 0:
                shaderContents += 'ArchiveEnd' + nextLineStr + nextLineStr
                ribContents += lineContents
                startShader = False
                continue
                
            shaderContents += lineContents
    
    f.close()
    
    # write and overwrite:
    f = open(ribPath, "w")
    
    f.write('Attribute "procedural" "reentrant" [ 0 ] ' + nextLineStr)
    f.write('Declare "depthfilter" "string" ' + nextLineStr)
    f.write('Declare "jitter" "integer" ' + nextLineStr)
    f.write('Declare "transmission" "string" ' + nextLineStr)
    f.write('Declare "motion_vector" "varying vector" ' + nextLineStr)
    f.write('Declare "P" "vertex point" ' + nextLineStr)
    f.write('Declare "st" "facevarying float[2]" ' + nextLineStr)
    f.write('Declare "decay" "float" ' + nextLineStr)
    f.write('Declare "mapname" "string" ' + nextLineStr)
    f.write('Declare "traname" "string" ' + nextLineStr)
    f.write('Declare "diffusecolor" "color" ' + nextLineStr)
    f.write('Declare "ambientcolor" "color" ' + nextLineStr)
    f.write('Declare "Km" "float" ' + nextLineStr)
    f.write('Declare "shadowmap" "string" ' + nextLineStr)
    f.write('Declare "shadowname" "string" ' + nextLineStr)
    f.write('Declare "samples" "float" ' + nextLineStr)
    f.write('Declare "displacements" "integer" ' + nextLineStr)
    f.write('Declare "transmission" "integer" ' + nextLineStr)
    f.write('Declare "specular" "integer" ' + nextLineStr)
    f.write('Declare "transmissionhitmode" "string" ' + nextLineStr)
    f.write('Declare "specularhitmode" "string" ' + nextLineStr + nextLineStr + nextLineStr)
    
    f.write(shaderContents)
    f.write(nextLineStr + nextLineStr + nextLineStr + nextLineStr + nextLineStr)
    f.write(ribContents)
    f.close()
    


        
def McdRecordUdimInfo():
    # find all agent geo
    # find all shaders
    # for each shader:
    #     test is this can be randmize
    #     if can: find all obj relative with this shader
    #         duplicate shaders node based on number
    
    # cmds.setAttr("McdTexInfo1.orgFullName[0]", "E:/Udim/formal_cloth1_color_<udim>_0.jpg", type = "string")
    # cmds.setAttr("McdTexInfo1.orgNamePre[0]", "E:/Udim/formal_cloth1_color_<udim>_", type = "string")
    # cmds.setAttr("McdTexInfo1.orgExt[0]", ".jpg", type = "string")
    # cmds.setAttr("McdTexInfo1.startID[0]", 0)
    # cmds.setAttr("McdTexInfo1.endID[0]", 4)
    # 
    # cmds.setAttr("McdTexInfo1.orgFullName[1]", "_NULL_", type = "string")
    
    # return
    
    textureInfoCollectList = []
    
    # find all agent geo -------------------------------------------------------
    allGeoGrp = cmds.ls("*Geometry_*")
    allGeoGrpRef = cmds.ls("*:Geometry_*")
    allGeoGrp.extend(allGeoGrpRef)
    if McdGeneral.McdIsBlank(allGeoGrp):
        return
    allGeoGrpList = []
    for i in range(len(allGeoGrp)):
        geoGrpParent = cmds.listRelatives(allGeoGrp[i], p = True, c = False)
        if McdGeneral.McdIsBlank(geoGrpParent):
            continue
        if cmds.nodeType(geoGrpParent[0]) == "McdAgentGroup":
            allGeoGrpList.append(allGeoGrp[i])
    
    allGeos = []
    for i in range(len(allGeoGrpList)):
        allSubNodes = cmds.listRelatives(allGeoGrpList[i], c = True, p = False, ad = True, path = True)
        if McdGeneral.McdIsBlank(allSubNodes):
            continue
        for j in range(len(allSubNodes)):
            if cmds.nodeType(allSubNodes[j]) == "mesh":
                if not cmds.getAttr(allSubNodes[j] + ".intermediateObject"):
                    canAdd = True
                    try:
                        if cmds.getAttr(allSubNodes[j] + ".autoTex"):
                            canAdd = False
                    except:
                        pass
                    
                    # bypass the texture sequence ones
                    if canAdd:
                        allGeos.append(allSubNodes[j])
    if allGeos == []:
        return
    
    # find all shaders ---------------------------------------------------------
    allShdGrp = []
    for i in range(len(allGeos)):
        allConns = cmds.listConnections(allGeos[i], d = True, s = False)
        if McdGeneral.McdIsBlank(allConns):
            continue
        for j in range(len(allConns)):
            if cmds.nodeType(allConns[j]) == "shadingEngine":
                if allConns[j] not in allShdGrp:
                    allShdGrp.append(allConns[j])
    if allShdGrp == []:
        return
    
    
    allShaders = []
    for i in range(len(allShdGrp)):
        allConns = cmds.listConnections(allShdGrp[i], s = True, d = False, p = True)
        if McdGeneral.McdIsBlank(allConns):
            continue
        for j in range(len(allConns)):
            if allConns[j].find(".outColor") > 0:
                shaderName = allConns[j].split(".outColor")[0]
                if shaderName not in allShaders:
                    allShaders.append(shaderName)
            ############### v add v ###############
            elif allConns[j].find(".outValue") > 0:
                shaderName = allConns[j].split(".outValue")[0]
                if shaderName not in allShaders:
                    allShaders.append(shaderName)
            ############### ^ add ^ ###############

    if allShaders == []:
        return


    # for each shaders: --------------------------------------------------------
    for i in range(len(allShaders)):
        # test is this can be randmize
        # find outColor node, "file" node --------------------------------------
        currentShader = allShaders[i]
        
        if cmds.nodeType(currentShader) == "McdRMShader" or cmds.nodeType(currentShader) == "McdRMDispMat":
            allShaderUDA = cmds.listAttr(currentShader, ud = True)
            if allShaderUDA != None and allShaderUDA != []:
                for j in range(len(allShaderUDA)):
                    udaType = cmds.attributeQuery(allShaderUDA[j], node = currentShader, at = True)
                    if udaType == "typed":
                        getVal = ""
                        try:
                            getVal = cmds.getAttr(currentShader + "." + allShaderUDA[j])
                        except:
                            continue
                        if getVal == "":
                            continue
                        try:
                            randList = udimSwapTestRMan(getVal)
                            if len(randList) > 0:
                                textureInfoCollectList.append(getVal)
                                textureInfoCollectList.append(randList)
                        except:
                            pass
            
            
        else:
            allHis = cmds.listHistory(currentShader)
            if McdGeneral.McdIsBlank(allHis):
                continue
            allFileNodes = []
            for j in range(len(allHis)):
                if cmds.nodeType(allHis[j]) == "file":
                    allFileNodes.append(allHis[j])
            if allFileNodes == []:
                continue
            
            
            for j in range(len(allFileNodes)):
                if cmds.nodeType(allFileNodes[j]) == "file":
                    texTemp = cmds.getAttr(allFileNodes[j] + ".fileTextureName")
                    
                randList = udimSwapTestRMan(texTemp)
                if len(randList) > 0:
                    textureInfoCollectList.append(texTemp)
                    textureInfoCollectList.append(randList)
        
    
    if len(textureInfoCollectList) <= 0:
        return;
    
    # find text node
    # assign info
    allTexNodes = cmds.ls(type = "McdTexInfo")
    if McdGeneral.MIsBlank(allTexNodes):
        return;
    
    texNode = allTexNodes[0]
    
    counter = 0
    while(1):
        strc = str(counter)
        getStr = cmds.getAttr(texNode + ".orgFullName[" + strc + "]")
        if getStr == "_NULL_" or len(getStr) < 1:
            break
        counter += 1
    
    # add from i:
    print "from " + str(counter)
    
    for i in range(len(textureInfoCollectList) / 2):
        texFullName = textureInfoCollectList[i*2+0]
        texIDList = textureInfoCollectList[i*2+1]
        
        lastUSId = texFullName.rfind("_")
        texPreName = texFullName[0:lastUSId + 1]
        texExt = texFullName.split(".")[-1]
        texExt = "." + texExt
        strc = str(counter)
        cmds.setAttr(texNode + ".orgFullName[" + strc + "]", texFullName, type = "string")
        cmds.setAttr(texNode + ".orgNamePre[" + strc + "]", texPreName, type = "string")
        cmds.setAttr(texNode + ".orgExt[" + strc + "]", texExt, type = "string")
        cmds.setAttr(texNode + ".startID[" + strc + "]", texIDList[0])
        cmds.setAttr(texNode + ".endID[" + strc + "]", texIDList[-1])
        
        counter += 1
        
    strc = str(counter)
    cmds.setAttr(texNode + ".orgFullName[" + strc + "]", "_NULL_", type = "string")
        
        
    
    
    
def udimSwapTestRMan(inTex):
    
    if inTex.find("<udim>") > 0:
        print "* In Tex: " + inTex
        dirName = os.path.dirname(inTex)
        imgName = os.path.basename(inTex)
        
        extName = imgName.split(".")[-1]
        extName = "." + extName
        
        imgSeg = imgName.split("<udim>")
        pattern = re.compile(imgSeg[0] + "\d\d\d\d*")
        # print '* re pattern: '+ imgSeg[0] + "\d\d\d\d*"
        # print "* Tex Folder: " + dirName
        if not os.access(dirName, os.R_OK):
            print "* Cannot access " + dirName
            return []
        
        allFiles = os.listdir(dirName)
        
        if allFiles == []:
            print "* No files found."
            return []
        
        allFiles.sort()
        
        matchList = []
        for i in range(len(allFiles)):
            isMatch = pattern.match(allFiles[i])
            
            if isMatch:
                matchList.append(allFiles[i])
                        
        print "* match num1 ***** : " + str(len(matchList))
        
        if len(matchList) > 1:            
            matchList2 = []
            for i in range(len(matchList)):
                if matchList[i].find(extName) > 0:
                    matchList2.append(matchList[i])
                    
            print "* match num2 *****: " + str(len(matchList2))
            
            if len(matchList2) > 1:
                # use the first match remain!
                baseName = matchList2[0]                                        # kkk_ggg_0.jpg             (base)
                baseNameExt = baseName.split(".")[-1]                           # jpg                       (extension)
                baseNamePre = baseName.split("." + baseNameExt)[0]              # kkk_ggg_0                 (base pre)
                lastUS = baseNamePre.rfind("_")
                if lastUS <= 0:
                    return []
                baseNamePrePre = baseNamePre[0 : lastUS]                        # kkk_ggg                   (base pre pre)
                baseNamePreIdStr = baseNamePre[lastUS+1 : len(baseNamePre)]     # 0                         (pre id)
                
                if not baseNamePreIdStr.isdigit():
                    return []
                
                baseNamePreId = int(baseNamePreIdStr)
                baseNamePreIdStr = str(baseNamePreId)
                
                newPath = dirName + "/" + baseNamePrePre + "_" + baseNamePreIdStr + "." + baseNameExt
                if not os.access(newPath, os.R_OK):
                    return []
                
                allPathsExtra = []
                allPathsExtra.append(baseNamePreId)
                while(True):
                    baseNamePreId +=1
                    baseNamePreIdStr = str(baseNamePreId)
                    newPath = dirName + "/" + baseNamePrePre + "_" + baseNamePreIdStr + "." + baseNameExt
                    
                    if not os.access(newPath, os.R_OK):
                        break
                
                    allPathsExtra.append(baseNamePreId)
                    
                print "* match num3 *****: " + str(len(allPathsExtra))
                print allPathsExtra
                
                return allPathsExtra
                
        else:
            return []
        
        
    return []
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        