## +
## ===================================================================
## Copyright(C) 2010 - 2014 Basefount Software Limited.
## and/or its licensors.  All rights reserved.
##
## The coded instructions, statements, computer programs, and/or
## related material (collectively the "Data") in these files contain
## unpublished information proprietary to Basefount Technology
## Limitd. ("Basefount") and/or its licensors, which is
## protected by Chinese copyright law and by international treaties.
##
## The Data is provided for use exclusively by You. You have the right 
## to use, modify, and incorporate this Data into other products for 
## purposes authorized by the Basefount software license agreement, 
## without fee.
##
## The copyright notices in the Software and this entire statement, 
## including the above license grant, this restriction and the 
## following disclaimer, must be included in all copies of the 
## Software, in whole or in part, and all derivative works of 
## the Software, unless such copies or derivative works are solely 
## in the form of machine-executable object code generated by a 
## source language processor.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
## BASEFOUNT DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR
## IMPLIED WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES
## OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
## PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
## TRADE PRACTICE. IN NO EVENT WILL BASEFOUNT AND/OR ITS LICENSORS 
## BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
## DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF BASEFOUNTAIN 
## AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
## OR PROBABILITY OF SUCH DAMAGES.
##
## ===================================================================
## -

## +
## ===================================================================
##  Module Name: McdMiarmyGlobal
##
##  Description:
##    Miarmy Global
##
## ===================================================================
## -

import maya.cmds as cmds
import maya.mel as mel
from McdGeneral import *
from McdSimpleCmd import *

import McdMiarmyTools
reload(McdMiarmyTools)
from McdMiarmyTools import *

def McdMiarmyToolsGUI():
    
    winName = "McdMiarmyTools"
    if cmds.window(winName, ex = True):
        cmds.deleteUI(winName)
    
    activeName = McdGetActiveAgentName()
        
    cmds.window(winName, title = "Cache Tools",rtf =True,menuBar=True, width=250)
    cmds.menu( label='Options')
    cmds.menuItem( label='Refresh contents', c = "McdRefreshMiarmyTools()")
    cmds.menuItem( label='Help' )
    cmds.menuItem( divider=True )
    cmds.menuItem( label='Exit', c = "McdExitMiarmyTools()" )

    form = cmds.formLayout()
    tabs = cmds.tabLayout(innerMarginWidth=5, innerMarginHeight=5)
    cmds.formLayout( form, edit=True, attachForm=((tabs, 'top', 0), (tabs, 'left', 0), \
                                                (tabs, 'bottom', 0), (tabs, 'right', 0)) )
    
    
    
    
    
    
    #--------------------------  Main GUI  --------------------------#
    globalNode = McdListMcdGlobal()
    brainNode = McdListMcdBrain()
    
    dEnableCache = cmds.getAttr(globalNode + ".enableCache")
    try:
        cmds.setAttr(globalNode + ".cacheTrans", 1)
    except:
        pass
    dCacheTrans = cmds.getAttr(globalNode + ".cacheTrans")
    dCacheScale = cmds.getAttr(globalNode + ".cacheScale")
    dCacheAction = cmds.getAttr(globalNode + ".cacheAction")
    dCacheVis = cmds.getAttr(globalNode + ".cacheVis")
    
    dCacheFolder = cmds.getAttr(globalNode + ".cacheFolder")
    if dCacheFolder == None:
        dCacheFolder = ""
    dCacheName = cmds.getAttr(globalNode + ".cacheName")
    if dCacheName == None:
        dCacheName = ""
    dCacheOffset = cmds.getAttr(globalNode + ".cacheOffset")
    dDisCallCheck = cmds.getAttr(globalNode + ".disableCB")
    dGenFootLoc = cmds.getAttr(globalNode + ".genFootLoc")
    
    child0 = cmds.columnLayout(adj = True)
    cmds.columnLayout(adj = True)

    cmds.text(l = "Agent Cache Options", fn = "smallBoldLabelFont", align = "left", h = 20)
    cmds.checkBoxGrp("mmc_ec", l = "Enable Agent Cache", v1 = dEnableCache, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_ec", "'+globalNode+'", "enableCache")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_ec", "'+globalNode+'", "enableCache")')
    
    cmds.textFieldGrp("mcc_cf", l = "Cache Folder", tx = dCacheFolder, cc = "MiarmyCacheCheckExistanceAndFill(\"" + globalNode + "\")")
    cmds.textFieldGrp("mcc_cn", l = "Cache Name", tx = dCacheName, cc = "MiarmyCacheChangeCacheName(\"" + globalNode + "\")")
    cmds.intFieldGrp("mmc_cof", l = "Cache Offset", v1 = dCacheOffset, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(1, "mmc_cof", "'+globalNode+'", "cacheOffset")')
    cmds.button("mcc_mkch", l = "Make Agent Cache", c = "McdMakeAgentCache()")
    
    
    cmds.text(l = "Auxiliary Cache Options", fn = "smallBoldLabelFont", align = "left", h = 20)
    cmds.checkBoxGrp("mmc_ict", l = "Is Cache Bone Translate", v1 = dCacheTrans, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_ict", "'+globalNode+'", "cacheTrans")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_ict", "'+globalNode+'", "cacheTrans")')
    cmds.checkBoxGrp("mmc_cvis", l = "Cache Agent Visibility", v1 = dCacheVis, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_cvis", "'+globalNode+'", "cacheVis")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_cvis", "'+globalNode+'", "cacheVis")')
    cmds.checkBoxGrp("mmc_gfloc", l = "Generate Foot Locator", v1 = dGenFootLoc, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_gfloc", "'+globalNode+'", "genFootLoc")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_gfloc", "'+globalNode+'", "genFootLoc")')
    cmds.checkBoxGrp("mmc_css", l = "Cache Agent Scale", v1 = dCacheScale, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_css", "'+globalNode+'", "cacheScale")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_css", "'+globalNode+'", "cacheScale")')
    cmds.checkBoxGrp("mmc_cact", l = "Cache Agent Action Info", v1 = dCacheAction, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_cact", "'+globalNode+'", "cacheAction")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "mmc_cact", "'+globalNode+'", "cacheAction")')
    
    cmds.text(l = "")
    cmds.text(l = "Agent Cache Merge Tools", fn = "smallBoldLabelFont", align = "left", h = 20)
    cmds.button("mcc_mgagch", l = "Merge", c = "McdMergeAgentCache()")


    # layer cache menu:
    allPlaces = cmds.ls(type = "McdPlace")
    if not MIsBlank(allPlaces):
        allPlaces.sort()
        
        for i in range(len(allPlaces)):
            enableCache = cmds.getAttr(allPlaces[i] + ".enableCache")
            if enableCache == 1:
                allPlaces[i] = "  ==  " + allPlaces[i]
            elif enableCache == 2:
                allPlaces[i] = "  >>  " + allPlaces[i]
        
        cmds.text(l = "")
        cmds.text(l = "Layer Agent Cache (Placement Based)", fn = "smallBoldLabelFont", align = "left", h = 20)    
        cmds.textScrollList("layercache_tsl", numberOfRows = 16, append = allPlaces, ams = True)
        cmds.rowColumnLayout(nc = 4, cw = [(1, 80),(2,80),(3, 120), (4, 120)])
        cmds.button(l = "Enable", c = "enableLayerCache(1)")
        cmds.button(l = "Disable", c = "enableLayerCache(0)")
        cmds.text(l = "")
        cmds.button(l = "Make Cache", c = "McdMakeAgentLCache()")
        cmds.setParent("..")
    

    cmds.setParent("..")
    cmds.setParent("..")
    
    
    
    # ///////////////////////////////////////////////////////////////////////////
    dEnableMeshDrive = cmds.getAttr(globalNode + ".enableMeshDrv")
    dEnableMDFeedback = cmds.getAttr(globalNode + ".meshDrvFB")
    dStartAgent = cmds.getAttr(globalNode + ".startAgent")
    dEndAgent = cmds.getAttr(globalNode + ".endAgent")
    
    
    # -------------------------------------------------------------------------------
    child1 = cmds.columnLayout(adj = True)
    
    dCharID = cmds.getAttr(brainNode + ".charId")
    dEnChar = cmds.getAttr(brainNode + ".enableChar")
    dDriveMid = cmds.getAttr(brainNode + ".driveMidRig")
    
    dSCCacheFolder = cmds.getAttr(globalNode + ".scFolder")
    if dSCCacheFolder == None:
        dSCCacheFolder = ""
    dSCCacheName = cmds.getAttr(globalNode + ".scName")
    if dSCCacheName == None:
        dSCCacheName = ""
        
    dSCStride = cmds.getAttr(globalNode + ".scStride")
    
    cmds.text(l = "Character Cache", fn = "smallBoldLabelFont", align = "left", h = 20)
    
    cmds.textFieldGrp("mmc_cf", l = "Cache Folder", tx = dSCCacheFolder, cc = "MiarmySCCacheCheckExistanceAndFill(\"" + globalNode + "\")")
    cmds.button(l = "Convert Agent Cache to Character Cache (By Character)", h = 30, c = "convertSCCache()")
    cmds.intFieldGrp("std_ifg", l = "Stride by Frame ( >= 1 )", v1 = dSCStride, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(1, "std_ifg", "'+globalNode+'", "scStride")')
    cmds.button(l = "Create Character Cache (By Frame)", h = 30, c = "convertSCCache2()")
    cmds.checkBoxGrp("enchar_cbg", l = "Enable Character Cache:", v1 = dEnChar, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "enchar_cbg", "'+brainNode+'", "enableChar")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "enchar_cbg", "'+brainNode+'", "enableChar")')
    cmds.intFieldGrp("scaid_ifg", l = "Character ID:", v1 = dCharID, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(1, "scaid_ifg", "'+brainNode+'", "charId")')





    dExpMiscMode = int(cmds.getAttr(globalNode + ".floatMaster[6]") + 0.01)
    dExpStartAgentID = int(cmds.getAttr(globalNode + ".floatMaster[4]") + 0.01)
    dExpEndAgentID = int(cmds.getAttr(globalNode + ".floatMaster[5]") + 0.01)
    
    dExpFolder = cmds.getAttr(globalNode + ".cmdMaster[10]")
    if dExpFolder == None:
        dExpFolder = ""
    dExpName = cmds.getAttr(globalNode + ".cmdMaster[11]")
    if dExpName == None:
        dExpName = ""
    
    cmds.text(l = "\nMisc Exporter", fn = "smallBoldLabelFont", align = "left", h = 20)
    cmds.rowColumnLayout(nc = 3, cw = [(1, 68),(2,75),(3, 100)])
    cmds.text(l = "")
    cmds.text(l = "Export Mode:")
    cmds.optionMenu("ModeStat_om", cc = 'om_cc_Mode("ModeStat_om", "'+globalNode+'", "floatMaster[6]")')
    setupOmStateExp(dExpMiscMode)
    cmds.setParent("..")
    
    cmds.intFieldGrp("said_ifg", l = "Start Agent ID:", v1 = dExpStartAgentID, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(1, "said_ifg", "'+ globalNode +'", "floatMaster[4]")')
    cmds.intFieldGrp("eaid_ifg", l = "End Agent ID:", v1 = dExpEndAgentID, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(1, "eaid_ifg", "'+ globalNode +'", "floatMaster[5]")')
    
    cmds.textFieldGrp("expdir_cf", l = "Export Folder:", tx = dExpFolder, \
                      cc = 'setSingleNumericAttrFieldGrpMiGA(3, "expdir_cf", "'+globalNode+'", "cmdMaster[10]")')
    cmds.textFieldGrp("expname_cf", l = "Export Name:", tx = dExpName, \
                      cc = 'setSingleNumericAttrFieldGrpMiGA(3, "expname_cf", "'+globalNode+'", "cmdMaster[11]")')
    cmds.rowColumnLayout(nc = 2, cw = [(1, 188),(2,188)])
    cmds.button(l = "Export", h = 30, c = 'exportMiscUseCharCache("' + globalNode + '", "' + brainNode + '")')
    cmds.button(l = "Import", h = 30, c = 'importMiscUseCharCache("' + globalNode + '", "' + brainNode + '")')
    cmds.setParent("..")



    cmds.text(l = "")
    cmds.text(l = "Middle Rig", fn = "smallBoldLabelFont", align = "left", h = 20)
    
    cmds.rowColumnLayout(nc = 2, cw = [(1, 188),(2,188)])
    cmds.button(l = "Build Middle Rig (Same as Rig)", h = 30, c = "createMiddleRig(1)")
    cmds.button(l = "Build Middle Rig (Add Suffix)", h = 30, c = "createMiddleRig(0)")
    cmds.setParent("..")

    cmds.checkBoxGrp("drvmr_cbg", l = "Drive Middle Rig", v1 = dDriveMid, \
                   on1 = 'setSingleNumericAttrSliderGrpMiG(0, "drvmr_cbg", "'+brainNode+'", "driveMidRig")',\
                   of1 = 'setSingleNumericAttrSliderGrpMiG(0, "drvmr_cbg", "'+brainNode+'", "driveMidRig")')
    
    
    
    
    cmds.text(l = "")
    cmds.text(l = "FBX Exporter", fn = "smallBoldLabelFont", align = "left", h = 20)
    cmds.button(l = "Export to FBX, one agent one file", h = 30, c = 'bakeAndExportFBX("' + globalNode + '", "' + brainNode + '")')

    cmds.setParent( '..' )
    
    
    
    
    
    
    # -------------------------------------------------------------------------------
    child2 = cmds.columnLayout(adj = True)
    
    cmds.text(l = "")
    cmds.text(l = "Foot Map Options", fn = "smallBoldLabelFont", align = "left", h = 20)

    # ///////////////////////////////////////////////////////////////////////////
    dFootMapFolder = cmds.getAttr(globalNode + ".footMapPath")
    if dFootMapFolder == None:
        dFootMapFolder = ""
        
    dFootMapName = cmds.getAttr(globalNode + ".footMapName")
    if dFootMapName == None:
        dFootMapName = ""
    dFootMapRes = cmds.getAttr(globalNode + ".footMapRes")
    dFootMapLife = cmds.getAttr(globalNode + ".footMapLife")
    dHeightThreshold = cmds.getAttr(globalNode + ".heightThreshold")
        
    cmds.textFieldGrp("fmf_tfg", l = "Foot Map Folder", tx = dFootMapFolder, cc = "MiarmyFootMapCheckExistanceAndFill(\"" + globalNode + "\")")
    cmds.textFieldGrp("fmn_tfg", l = "Foot Map Name", tx = dFootMapName, cc = "MiarmyFootMapChangeCacheName(\"" + globalNode + "\")")
    cmds.intFieldGrp("fmr_ifg", l = "Foot Map Resolution", v1 = dFootMapRes, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(1, "fmr_ifg", "'+globalNode+'", "footMapRes")')
    cmds.intFieldGrp("fml_ifg", l = "Foot Lifespan (frame uint)", v1 = dFootMapLife, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(1, "fml_ifg", "'+globalNode+'", "footMapLife")')
    cmds.floatFieldGrp("fmh_ffg", l = "Foot Height Threshold:", v1 = dHeightThreshold, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(2, "fmh_ffg", "'+globalNode+'", "heightThreshold")')
    cmds.text(l = "( Format Info: only .tga (TGA-32) )", align = "left", h = 20)
    cmds.button(l = "Make Foot Print Map", c = "McdMakeFootMap()")
    
    
    cmds.text(l = "")
    cmds.text(l = "Bake Agents To Skinned Actors", fn = "smallBoldLabelFont", align = "left")
    cmds.button(l = "Bake All", h = 30, c = "McdBakeAgentToAnimatedBone1(0)")
    cmds.button(l = "Bake Selected", h = 30, c = "McdBakeAgentToAnimatedBone1(1)")
    cmds.text(l = "")
    cmds.button(l = "Bake All (Only Bones)", h = 30, c = "McdBakeAgentToAnimatedBone1(0, 0)")
    cmds.button(l = "Bake Selected(Only Bones)", h = 30, c = "McdBakeAgentToAnimatedBone1(1, 0)")
    
    cmds.text(l = "")
    cmds.text(l = "After Baking", fn = "smallBoldLabelFont", align = "left")
    cmds.button(l = "Select Same Type Characters", c = "McdSelectSameTypeChar()")
    
    cmds.text(l = "")
    cmds.text(l = "Foot Locators", fn = "smallBoldLabelFont", align = "left")
    #cmds.button("mcdmkfootloc", label = "Bake Foot Locators", c = "McdMakeFootLocatorsSL()")
    cmds.button(l = "Bake Feet Locators", h = 40, c = 'bakeAndExportFBX("' + globalNode + '", "' + brainNode + '")')


    cmds.setParent( '..' )
    
    
    
    
    
    
   # -------------------------------------------------------------------------------
    child3 = cmds.columnLayout(adj = True)
    
    dExeSim = cmds.getAttr(globalNode + ".boolMaster[5]")
    dExeACache = cmds.getAttr(globalNode + ".boolMaster[6]")
    
    dTx = []
    for i in range(10):
        cmdStr = cmds.getAttr(globalNode + ".cmdMaster[" + str(i) + "]")
        if cmdStr == None:    
            dTx.append("")
        else:
            dTx.append(cmdStr)
            

    cmds.text(l = "Callback Time", fn = "smallBoldLabelFont", align = "left", h = 30)
    cmds.checkBoxGrp("callsim", l = "When simulating & caching", v1 = dExeSim, \
                   cc = 'setSingleNumericAttrSliderGrpMiCallback(0, "callsim", "'+globalNode+'", "boolMaster[5]")')
    cmds.checkBoxGrp("callch",  l = "When only caching", v1 = dExeACache, \
                   cc = 'setSingleNumericAttrSliderGrpMiCallback(0, "callch", "'+globalNode+'", "boolMaster[6]")')
    
    
    cmds.text(l = "\nPython Callback", fn = "smallBoldLabelFont", align = "left", h = 30)
    cmds.textFieldGrp("psp_tfg", l = "Pre Sim Python", tx = dTx[0], cc = 'McdCmdTxtFill("psp_tfg", 0, "' + globalNode + '")')
    cmds.textFieldGrp("pfpsp_tfg", l = "Pre Frame Python", tx = dTx[1], cc = 'McdCmdTxtFill("pfpsp_tfg", 1, "' + globalNode + '")')
    cmds.textFieldGrp("pofpsp_tfg", l = "Post Frame Python", tx = dTx[2], cc = 'McdCmdTxtFill("pofpsp_tfg", 2, "' + globalNode + '")')
    cmds.textFieldGrp("posp_tfg", l = "Post Sim Python", tx = dTx[3], cc = 'McdCmdTxtFill("posp_tfg", 3, "' + globalNode + '")')


    cmds.text(l = "\nMEL Callback", fn = "smallBoldLabelFont", align = "left", h = 30)
    cmds.textFieldGrp("psm_tfg", l = "Pre Sim MEL", tx = dTx[4], cc = 'McdCmdTxtFill("psm_tfg", 4, "' + globalNode + '")')
    cmds.textFieldGrp("pfpsm_tfg", l = "Pre Frame MEL", tx = dTx[5], cc = 'McdCmdTxtFill("pfpsm_tfg", 5, "' + globalNode + '")')
    cmds.textFieldGrp("pofpsm_tfg", l = "Post Frame MEL", tx = dTx[6], cc = 'McdCmdTxtFill("pofpsm_tfg", 6, "' + globalNode + '")')
    cmds.textFieldGrp("posm_tfg", l = "Post Sim MEL", tx = dTx[7], cc = 'McdCmdTxtFill("posm_tfg", 7, "' + globalNode + '")')
    
    cmds.text(l = "\nPost Placement Callback", fn = "smallBoldLabelFont", align = "left", h = 30)
    cmds.textFieldGrp("ppcmel_tfg", l = "Post Place MEL", tx = dTx[8], cc = 'McdCmdTxtFill("ppcmel_tfg", 8, "' + globalNode + '")')
    cmds.textFieldGrp("ppcpy_tfg", l = "Post Place Python", tx = dTx[9], cc = 'McdCmdTxtFill("ppcpy_tfg", 9, "' + globalNode + '")')
    
    
    cmds.setParent( '..' )
    
    
    
    child4 = cmds.columnLayout(adj = True)
    cmds.text(l = "Placement Seed", fn = "smallBoldLabelFont", align = "left", h = 30)
    
    dSeedRenderGeo = cmds.getAttr(globalNode + ".floatMaster[22]")
    cmds.floatFieldGrp("sdtbl_rg", l = "Random Geoemtries:", v1 = dSeedRenderGeo, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(2, "sdtbl_rg", "'+globalNode+'", "floatMaster[22]")')
    
    dSeedRenderTex = cmds.getAttr(globalNode + ".floatMaster[23]")
    cmds.floatFieldGrp("sdtbl_rt", l = "Random Textures:", v1 = dSeedRenderTex, \
                   cc = 'setSingleNumericAttrFieldGrpMiGA(2, "sdtbl_rt", "'+globalNode+'", "floatMaster[23]")')
    
    cmds.setParent( '..' )
    
    
    
    
    cmds.tabLayout( tabs, edit=True, tabLabel=((child0, "Cache Tools"), \
                                             (child1, "Character Cache"), \
                                             (child2, "Bake Tools"), \
                                             (child3, "Callbacks"), \
                                             (child4, "Seed")))
    cmds.showWindow(winName)

def McdRefreshMiarmyTools():
    McdMiarmyToolsGUI()

def McdExitMiarmyTools():
    try:
        cmds.deleteUI("McdMiarmyTools")
    except:
        pass
























