## +
## ===================================================================
## Copyright(C) 2010 - 2014 Basefount Software Limited.
## and/or its licensors.  All rights reserved.
##
## The coded instructions, statements, computer programs, and/or
## related material (collectively the "Data") in these files contain
## unpublished information proprietary to Basefount Technology
## Limitd. ("Basefount") and/or its licensors, which is
## protected by Chinese copyright law and by international treaties.
##
## The Data is provided for use exclusively by You. You have the right 
## to use, modify, and incorporate this Data into other products for 
## purposes authorized by the Basefount software license agreement, 
## without fee.
##
## The copyright notices in the Software and this entire statement, 
## including the above license grant, this restriction and the 
## following disclaimer, must be included in all copies of the 
## Software, in whole or in part, and all derivative works of 
## the Software, unless such copies or derivative works are solely 
## in the form of machine-executable object code generated by a 
## source language processor.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
## BASEFOUNT DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR
## IMPLIED WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES
## OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
## PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
## TRADE PRACTICE. IN NO EVENT WILL BASEFOUNTAIN AND/OR ITS LICENSORS 
## BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
## DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF BASEFOUNTAIN 
## AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
## OR PROBABILITY OF SUCH DAMAGES.
##
## ===================================================================
## -

## +
## ===================================================================
##  Module Name: McdAgentManager.py
##
##  Description:
##    For managing agent in scene, globally.
##
## ===================================================================
## -

import maya.cmds as cmds
from McdGeneral import *
from McdSimpleCmd import *
from McdReSeedManagerGUI import *

def McdReSeedManagerStartUpSetup():
    info = []
    
    # find terrain node, get terrain mesh:
    globalNode = McdGetMcdGlobalNode()
    
    indexCounter = 0
    while(1):
        d1 = cmds.getAttr(globalNode + ".reseed[" + str(indexCounter) + "]")
        d2 = cmds.getAttr(globalNode + ".reseed[" + str(indexCounter+1) + "]")
        
        info.append(d1)
        info.append(d2)
        
        if d1 <= -1:
            break
        
        indexCounter += 2
            
    return info


def changeRSAgentID(index):
    
    globalNode = McdGetMcdGlobalNode()
    
    stri = str(index)
    
    setValue = cmds.intField("agtid_if" + stri, q = True, v = True)
    
    index *= 2
    
    cmds.setAttr(globalNode + ".reseed[" + str(index) + "]", setValue)


def changeRSOffset(index):
    

    globalNode = McdGetMcdGlobalNode()
    
    stri = str(index)
    
    setValue = cmds.intField("seedoff_if" + stri, q = True, v = True)
    
    index *= 2
    
    cmds.setAttr(globalNode + ".reseed[" + str(index+1) + "]", setValue)







    
    
    