## +
## ===================================================================
## Copyright(C) 2010 - 2014 Basefount Software Limited.
## and/or its licensors.  All rights reserved.
##
## The coded instructions, statements, computer programs, and/or
## related material (collectively the "Data") in these files contain
## unpublished information proprietary to Basefount Technology
## Limitd. ("Basefount") and/or its licensors, which is
## protected by Chinese copyright law and by international treaties.
##
## The Data is provided for use exclusively by You. You have the right 
## to use, modify, and incorporate this Data into other products for 
## purposes authorized by the Basefount software license agreement, 
## without fee.
##
## The copyright notices in the Software and this entire statement, 
## including the above license grant, this restriction and the 
## following disclaimer, must be included in all copies of the 
## Software, in whole or in part, and all derivative works of 
## the Software, unless such copies or derivative works are solely 
## in the form of machine-executable object code generated by a 
## source language processor.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
## BASEFOUNT DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR
## IMPLIED WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES
## OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
## PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
## TRADE PRACTICE. IN NO EVENT WILL BASEFOUNTAIN AND/OR ITS LICENSORS 
## BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
## DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF BASEFOUNTAIN 
## AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
## OR PROBABILITY OF SUCH DAMAGES.
##
## ===================================================================
## -

## +
## ===================================================================
##  Module Name: Geometry Hide Manger
##
##  Description:
##    bake geometry hidden info!
##
## ===================================================================
## -

import maya.cmds as cmds
from McdGeneral import *
from McdSimpleCmd import *

import McdReSeedManager
reload(McdReSeedManager)
from McdReSeedManager import *


def McdReSeedManagerGUI():
    
    winName = "McdReSeedManager"
    if cmds.window(winName, ex = True):
        cmds.deleteUI(winName)
    cmds.window(winName, title = "Global Re-seed Manager",rtf =True,menuBar=True, width=200)
    
    cmds.menu( label='Options')
    cmds.menuItem( label='Refresh contents', c = "McdRefreshReSeedManager()")
    cmds.menuItem( label='Help' )
    cmds.menuItem( divider=True )
    cmds.menuItem( label='Exit', c = "McdExitReSeedManager()" )
    
    form = cmds.formLayout()
    tabs = cmds.tabLayout(innerMarginWidth=5, innerMarginHeight=5)
    cmds.formLayout( form, edit=True, attachForm=((tabs, 'top', 0), (tabs, 'left', 0), \
                                                (tabs, 'bottom', 0), (tabs, 'right', 0)) )
    
    #-------------------------  Initialize  -------------------------#
    ## get contents here:
    info = McdReSeedManagerStartUpSetup()
    
    #--------------------------  Main GUI  --------------------------#
    child0 = cmds.columnLayout(adj = True)

    
    cmds.rowColumnLayout(nc = 2, cw = [(1,120),(2,120)])
    cmds.text(l = "Agent ID", align = "left", font = "smallBoldLabelFont")
    cmds.text(l = "Seed Offset", align = "left", font = "smallBoldLabelFont")

    # fill contents here:
    if info != []:
        for i in range(len(info) / 2):
            stri = str(i)
            cmds.intField("agtid_if" + stri, v = info[i*2], cc = "changeRSAgentID(" +stri+ ")")
            cmds.intField("seedoff_if" + stri, v = info[i*2+1], cc = "changeRSOffset(" +stri+ ")")
            
    cmds.button(l = "Expand", c = "McdRefreshReSeedManager()")
    
    cmds.setParent("..")
    
    cmds.setParent("..")
    
    
    #------------------------------- Cricial Help --------------------------------#
    child1 = cmds.columnLayout(adj = True)
    cmds.text(l = "* Control Global Re-seed Information", fn = "smallBoldLabelFont", align = "left")
    cmds.text(l = "      Rules: agent id -> seed offset", align = "left")
    
    cmds.separator(h = 10)
    cmds.button(l = "Check detailed help")
    
    cmds.setParent( '..' )
    
    
    cmds.tabLayout( tabs, edit=True,tabLabel=((child0, "Re-Seed in Scene"),(child1, "Quick Tips")))
    cmds.showWindow(winName)



def McdRefreshReSeedManager():
    McdReSeedManagerGUI()

def McdExitReSeedManager():
    try:
        cmds.deleteUI("McdReSeedManager")
    except:
        pass
