#!/bin/sh

#
# This sample script shows how to render a Maya scene from the command line
# using the mental ray standalone renderer.
#
if [ $# != 1 ]; then
    echo "Usage: $0 mayaSceneFile"
    exit 1
fi

if [ ! -r "$1" ]; then
    echo "Cannot read scene file '$1'."
    exit 2
fi

mayaCmd=maya

if [ "`uname`" = "Darwin" ]; then
    mayaCmd=Maya
fi

tempFile=$$.mi

$mayaCmd -batch -command "Mayatomr -mi -file \"$tempFile\" \"$1\""
ray -v 4 $tempFile

rm -f $tempFile
